-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "downloadable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "readable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "uploadable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "writable" INTEGER[] DEFAULT ARRAY[]::INTEGER[];

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "downloadable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "readable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "uploadable" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "writable" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
